import type { Metadata } from "next";
import { Geist, Limelight, Montserrat } from "next/font/google";
import "@/styles/globals.css";
import MobileHeader from "@/components/header/MobileHeader";
import DesktopHeader from "@/components/header/DesktopHeader";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const limelight = Limelight({
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal"],
  variable: "--font-limelight",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300"],
  style: ["normal"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <Head>
        <title>Art Portfolio</title>
        <meta name="description" content="Custom art and design projects" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body
        className={`${geistSans.variable} ${limelight.variable} ${montserrat.variable} antialiased`}
      >
        <MobileHeader />
        <DesktopHeader />
        {children}
      </body>
    </html>
  );
}
